name: Test

on:
  workflow_dispatch  :
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Debug

  #Set download URL for ARM Performance Libraries (APL)
  DOWNLOAD_URL: "https://developer.arm.com/-/cdn-downloads/permalink/Arm-Performance-Libraries/Version_24.10/arm-performance-libraries_24.10_Windows.msi" 


permissions:
  contents: read

jobs:
  build:
    runs-on: windows-11-arm

    steps:
    - uses: actions/checkout@v4

    - name: Check packages
      run: |
        python3 --version
        cmake --version
        file "C:\Program Files\CMake\bin\cmake.exe"
        file "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.exe"      
        git --version
        where git
        
        
